system:
  listenAddr: :9000
  use-multipoint: false

db:
  DriverName: mysql
  Database: gva
  Port: 3306
  UserName: root
  Password: root
  Host: 127.0.0.1
  Charset: utf8mb4

redis:
  Host: 127.0.0.1
  Port: 6379
  Password:
  db: 0

jwt:
  signing-key: 'YunKong'
  expires-time: 604800
  buffer-time: 86400
  issuer: 'YunKong'

zap:
  level: "info"
  format: 'console'
  prefix: '[personFrame]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true
